name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]

  # (optional) Run workflow manually
  workflow_dispatch:

  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Base
          base: header, activity, community, repositories #, metadata

          # ISO Calendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages plugin
          plugin_languages: yes
          plugin_languages_details: percentage

          # Lines plugin
          plugin_lines: yes
